name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -d "$HOME/cockroach-app" ]; then
              cd $HOME/cockroach-app
            elif [ -d "$HOME/cockroach-backend-server" ]; then
              cd $HOME/cockroach-backend-server
            else
              echo "Project directory not found!"
              exit 1
            fi
            
            if [ -d "backend" ]; then
              cd backend
            fi
            
            git pull origin main
            npm install
            npm run build
            pm2 restart all
